services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: user
      MARIADB_PASSWORD: mypassword
      MARIADB_DATABASE: example-database
    ports:
      - 3309:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080